name: ApacheAssignment

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  job1_ubuntu:
    runs-on: Ubuntu-Latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      # - name: SSH into EC2 instance
      #   run: |
      #     chmod 400 AkshatUbuntuKeyAWS27.pem
      #     ssh -i "AkshatUbuntuKeyAWS27.pem" ubuntu@ec2-100-25-36-218.compute-1.amazonaws.com
      - name: Root access and Update Sudo 
        run: |
          sudo -i
          sudo apt-get update
      - name: Install Apache Server
        run: |
          sudo apt-get install apache2
          systemctl apache start
           


          


  # job2_windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run a one-line script
  #       run: echo Hello, world in windows.

 

  # job3_python:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v2
  #     - name: Run a one-line script
  #       run: python Demo.py



  # job4_python:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v2
  #     - name: Run a one-line script
  #       run: python akt2.py
  #       working-directory: ./Scripts